// const math=require("./math.js");
// math.add(10,5);
// math.sub(10,5);
// math.mul(10,5);
// math.div(10,5);
const fs=require("fs");
fs.writeFileSync("hello.txt","hello world");
const data=fs.readFileSync("hello.txt","utf-8");
console.log(data);
fs.appendFileSync("hello.txt","\n hello me");
